version: "3.8"

services:
  web:
    build: .
    container_name: django-web
    command: python manage.py runserver 0.0.0.0:8000

    environment:
      DB_NAME: django_db
      DB_USER: django_user
      DB_PASSWORD: StrongPassword123
      DB_HOST: django-postgres-db.cv6m8aiiqflt.eu-north-1.rds.amazonaws.com
      DB_PORT: "5432"
      ALLOWED_HOSTS: "*"
      DEBUG: "False"

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    restart: always

